logging:
  level: debug

server:
  port: 8080
#  address: 127.0.0.1

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:32769/demo?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
  redis:
    host: 127.0.0.1
    port: 32772
    password:
    database: 0
