logging:
  level: debug

server:
  port: 80
#  address: 127.0.0.1

spring:
  datasource:
    url: jdbc:mysql://172.16.34.251:3306/answerduel?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
  redis:
    host:
    port:
    password:
    database:
